### ISSUE TITLE
Verification System: Randomly has an unknown message error

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#148]
```bash
/home/vylpes/vylbot/node_modules/discord.js/src/rest/RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (/home/vylpes/vylbot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/vylpes/vylbot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async MessageManager.delete (/home/vylpes/vylbot/node_modules/discord.js/src/managers/MessageManager.js:210:5)
    at async Message.delete (/home/vylpes/vylbot/node_modules/discord.js/src/structures/Message.js:792:5) {
  method: 'delete',
  path: '/channels/708683543764533348/messages/968234960949501972',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}
```

**Comment by Vylpes** [comment]
Not convinced this has been fixed even though it doesn't seem to be happening, going to give it a little bit more time to see if it comes back up again - check bot logs as I've temporarily got it to log errors

**Comment by Vylpes** [comment]
Can't find the issue, going to close
