### ISSUE TITLE
Bunny command: TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#162]
```bash
/home/vylpes/vylbot/node_modules/random-bunny/dist/index.js:41
            const randomSelect = data[random].data;
                                              ^

TypeError: Cannot read properties of undefined (reading 'data')
    at /home/vylpes/vylbot/node_modules/random-bunny/dist/index.js:41:47
    at Generator.next (<anonymous>)
    at fulfilled (/home/vylpes/vylbot/node_modules/random-bunny/dist/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Vylpes** [comment]
This is actually an issue with the random-bunny package
